[versions]
paper = "1.21.11-R0.1-SNAPSHOT"
junit = "6.0.3"
mockbukkit = "4.110.0"
jacoco = "0.8.14"
run-paper = "3.0.2"
spotless = "8.4.0"
hikaricp = "7.0.2"
flyway = "12.6.1"
sqlite-jdbc = "3.53.2.0"
postgresql = "42.7.11"
testcontainers = "1.21.4"

[libraries]
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v1.21", version.ref = "mockbukkit" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
